---
javascripts:
-#{ current_app_name }:
  - public/javascripts/jquery.js
  - public/javascripts/jquery.validate.js
  - public/javascripts/application.js

stylesheets:
-#{ current_app_name }:
  - public/stylesheets/screen.css